import = [
  "/Users/felix/.config/alacritty/colors.toml",
  "/Users/felix/.config/alacritty/fonts.toml"
]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 90
lines = 35

[window.padding]
x = 5
y = 5
