[font]
size = 19 

[font.bold]
family = "Victor Mono"
style = "SemiBold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "Victor Mono"
style = "Light"
