[font]
size = 21

[font.bold]
family = "VictorMono Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "SemiBold"
